language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script: nosetests  html2hamlpy --with-coverage --cover-package=html2hamlpy
after_success:
  coveralls
